[package]
name = "dabbit-producer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
envy = "0.4"
dotenv = "0.15.0"
lapin = "2.1.1"

[dev-dependencies]
